// Code generated by "file2go -v -t -o templates/files.go templates/*.html templates/*.js templates/*.css templates/*.ico"; DO NOT EDIT.

// Encoded files:
// → templates/icons.html
// → templates/index.html
// → templates/javascript.js
// → templates/style.css
// → templates/theme-default.css
// → templates/theme-juri.css
// → templates/favicon.ico

package templates

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io/ioutil"
)

var container map[string]*[]byte

// decode the base64Encoded string and return a *[]byte for the decoded data
func decode(base64Encoded string) (*[]byte, error) {
	gzipEncoded, err := base64.StdEncoding.DecodeString(base64Encoded)
	if err != nil {
		return nil, fmt.Errorf("failed to decode data(BASE64): %s", err)
	}

	var buf bytes.Buffer
	_, err = buf.Write(gzipEncoded)
	if err != nil {
		return nil, fmt.Errorf("failed buffer decode data: %s", err)
	}

	zr, err := gzip.NewReader(&buf)
	if err != nil {
		return nil, fmt.Errorf("failed to create reader from buffer: %s", err)
	}
	defer zr.Close()

	decoded, err := ioutil.ReadAll(zr)
	if err != nil {
		return nil, fmt.Errorf("failed to decode data(GZIP): %s", err)
	}

	return &decoded, nil
}

func init() {
	container = make(map[string]*[]byte)
	var err error
	
	container["templates/icons.html"], err = decode(`` +
    `H4sICAAAAAAA/2RHVnRjR3hoZEdWelhHbGpiMjV6TG1oMGJXdz0A7Fpfj9u4EX/fTz` +
    `GnQ4HeQeKSFKk/jrVAmyuQhxY9oEWA9k2WaFtdWTIk2Wun6HcvhqTXcuO15EXyoOKQ` +
    `YC3Kw5nf/OWQ9PyHX/768e//+PVPsO425dPDHD+gTKtV4qjKeXoAmK9VmuMDwHyjuh` +
    `Syddq0qkucXbf0Iqf/VZVuVOJs6kVRKu9FLbx0u/WydJsuSuVAVledqrrEOar2yrR9` +
    `oV62ddP1CF+KvFsnudoXmfL0wIWiKroiLb02S0uVMFfzAWjXTVE9e13tLYsuqeqTgL` +
    `Y7lurp4fFn+EUt013ZQZHVFejX8PPjA9HDfz8ALIuynEG2axpVdR/rsm4+PABoqTNg` +
    `aoOjtSpW6+51WO9VsyzrlxmsizxXFb7Li3ZbpsfZoqyz5w8nvlVdKRy0XVM/q1mj8v` +
    `PIszLC3/XelUWl/lUX1QyaelflHx7+8/Cw2HWdBbtN87yoVjMQ2wPO2qTNCompGS7S` +
    `7HmlJ87gR7XEf/p1ffDa4oueuKta1ZmXTa6aGfDtAdq6LHJYlKmBbr7ymjQvdu2rrJ` +
    `sm6dSh89KyWFUzyFTVqQahGx/NH6038PEUVvNFnR+ts37wPPikLWm8lKddCp53cuV+` +
    `BWlTpJ4xduJ0zU45sKyzXYsRljjLtGyVY5ybOCdPoO1tOCCX42ZRl1DkiYMyvKxoMo` +
    `xODL8/1ofEoUCB4//XOQBzQ6VnbT/aGdkhcRh1IDuazyZxIudp/mhon85Ka4lvAkCM` +
    `Q+K3abc2wn/V1Hni/AV814fPwEL4M7DQZRT+idKRdLzsdNcO6t6orLPCkZw6JgISRz` +
    `jW+4nDhAMH/eaYOD7iwFlvM2E3mDB+ncugNpU6dKMsqc3Hz+aLr1rvgpqxnrWjd1q7` +
    `Ufvx+FjUk8iGEcZncv4+fG1Xb8cHw980tfVidPZipJ0YaB8Gd/uwVWmTrcdbCV1HJP` +
    `guC69Yx6atzlTfZGqoE1US+Y5ULYv2zgD7BAI+gw/+TdcFmpJFSHqTkLshkZYpPoVG` +
    `jRuMDb1mPUTMXcYtb8aB8QHOmlgzHiDlLgteUetH/DPEPTgDv0Z+9tVbzlrWZa6ase` +
    `7aAHc5rEFCCb7LiYQ1aNkRfAJ+K5nezPb6ZVj8Cromrdpl3WxwPUurtkw79Xvqevyn` +
    `Ht0JaFvnxbbOi1l33KrESZvMOb/DKPeYJMLnkkqnNxl6RMfE4SSkvi+Z7E1uTM6exz` +
    `p7r/Nou7TBct0jV1WeOPSSXnvSY5ywmAYxc0MSSs7CUMAfIHADQIMw8FhMJOe+H7oh` +
    `obEvIhGev75g6HFKgjhyPUpY6HPKQv+CkU9iEdGIuZ5PGKOM+28xio2RROhes0W9fe` +
    `0uLqb1XNXUHfrJY4j+p69j+VQpbXkkoTwXSKw9WCJj/DwmjryyXD6uxgfaIq1Gti/j` +
    `Opb/zUSKeSjuXk26Jm3vKOSCSDdASRLXO59IV6deMLDqRab+R5p+YAVHGiTG1fQr2m` +
    `E7Z3XV7jaD7dK4RPVJENIgDHg/xC6ylPkk8GUYRPdk6YgctX4lMeMipmgKEkRCxr20` +
    `7DFk4FEiWMxk4PtIS7mMKbvIOyJjEbEYexQSypgzeTXvJGFSYhmIOOexL3o84pM13F` +
    `etoQQvcCl86at3JQN9eiX9emUdPe4Gup577O4gtj738kJvMfLfnP//4/xLSiwOWBvC` +
    `K53kcG1o1Falg71hrwwHF1VYXK3CF90rLha9Gf7tBvY2ztHh/L0Bf0sXtEW1Gr2RR4` +
    `ihxcdvaNRDx9wABLYWEvZXWt7hnY3G9x7Tf1ug3zTs0yqvN/f02JiKAZQgsK9YQzC0` +
    `c8BNQIQdgZ16t9kNxPsK+HfC+h7Lv6HViJ36GZokUu8DGXU5MGFGt3slpPwMV/fUPQ` +
    `tZFdbAbuzP3tBgU+T5cLpeKiGMEowaLcSAFjiFydc5pe4x5bDqLEbd79ZoUXfd+GSw` +
    `8JiFFxqVcDwID335Ga0/7J3wve7JSjW8rTgLEySIuC95jGs4ZSwMJK7r+hVzKaHclz` +
    `52EzIQIQ2wOgUhlVHU7xEYiSWPBXc9+8QwCAXx8ZFFZl9geLqcMKHF9OZHuMHEWS4j` +
    `PsqRMfYdKIYLlwMnfmjECyK0dA574CSOIg3vy03LX1NREKFfCZcFREBEqOGrhxp0D1` +
    `5IQiNIM9BPgxsWq45PuFGHMRJqvfUBCUN1gEnLTUvt21MQX2upBSLOgdi6wvyKSjej` +
    `LiBRbHgIEkitLzaJ2u4ychkR+mUAjHCXk8gw/zoIGMNtvv0aqOUVYGhIGw633IXLID` +
    `F0riCcGWU8RvQDQxzab/3woybQMHpiK+IE16UktsYm8jVGpdGqx8KjJDQ8vJMt5QDO` +
    `iODyQoTxr8eMowQmjTUffQ08+nVQ3Y5ZZGy9R03wM11BTlKgvLA8O0nmbyC/LBvzx3` +
    `a/ss3B3F5O2buXZV11Xlt8UTMQdHv44OjKkvauYfYryMq0bU29cUbd7PR03LUKDmVR` +
    `Pc/WjVomzo/9y5yn+eOu7XfF+9UJsYH5NArzdwarL34mAlXfE00Dq74FmgZUfSE0Da` +
    `j6bmgiUM0V0jTA6iulaUC1FyrTAGtuX6aBdZFWE0FqzvSngfV0XD8ptOdzimnAtuee` +
    `UwI7NRPbc80pgZ2aie0x5pTA3mXicVu07712TKaBtEeT0wBrTx2nAdacKo7COn80Pw` +
    `ydP5qfJv83AAD//7Z+OS6rLAAA`)
	if err != nil {
		panic(err)
	}
	container["templates/index.html"], err = decode(`` +
    `H4sICAAAAAAA/2RHVnRjR3hoZEdWelhHbHVaR1Y0TG1oMGJXdz0A7Fztj9s2k//ev2` +
    `Kq+3JFJa6ody3sPaRJej0g6S2SIPfyTbZom60s+iFp77pF//cHJCVZsmXL3no36YMC` +
    `RVekhvPymyE55MgZffvmv19/+r/7t7CQy+Lum5H6A0VWzscWKa27bwBGC5Ll6gFgtC` +
    `Qyg+ki44LIsbWWMyex2q/KbEnG1pJNaEGcBzJxstXKmWarbFIQC6aslKSUY2tLRM+w` +
    `DSUPK8Zli/CB5nIxzsmGTomjGzbQkkqaFY6YZgUZY1vzARALTstfHcmcGZXjktUCCl` +
    `r+CpwUY0vIbUHEghBpwYKTWdWDpkKcQywXZEmcnMyydSHbg751nNZoQ7yQciVub25m` +
    `rJQCzRmbFyRbUYGmbHkzFeI/ZtmSFtvxBzZhkn3/npXMqgzZF39X9TvO3dPF0PlCEr` +
    `YWp4WMJJUFufsfMoH3969HN6a5Dw2dsrIGZZZtVBPRKbNAbldkbNFlNic3j44m0wF0` +
    `U0fQaMLyLdB8bKmHFn6wyoSAVcazJZGEC5hxtoRlRks0ZyAZLGiekxJouVpLmFFS5G` +
    `IHSE43MC0yIcbWguakQWxkyJW8B1GrJ8mjtGCTFWsytn7/HT2IP/6oNbnJ6ebum51W` +
    `Hz//JygzjCzTLzZzyDjNHKPS2JJ8TSyYselaqDBXmBSCWKDRHVs5Fasi296WrGxpJr` +
    `bLCSu0akqAM6V8qqaImgM/sMex5YILnvqvGQMwMlQwfRxb2LVgujV/+dhKrLvRjXnd` +
    `yLgxQo7KVGoNSVxlcgH52HoPvu3DZ8AxvAMc29iF/1ci1fvzBWZrMWgjJ1MJZt5bgQ` +
    `ULokJ3bOHAgkfdsx1bvhKtCM8eh73+gYM6lyZczgTJ24GU9mLUoca4hWnyREw52Zyv` +
    `H05aEvGwhumO3HuafkKy1SUuT3auS7TnIu246GLHCZLx6eJ8aJS/UAi+jeMeSNozzz` +
    `czL9YTL0ThE6ZeQcUFUaXC5CcI4DP44J/0V6QpcaJIT4eenVYsU0gHWKY1y9OE2MZh` +
    `xROHgMMBrppYsz0kHcRvxoqc8HMRXIJne7CAEArwbQ+FsAAtOIGfwHvKpGMPw9LnIH` +
    `lWihnjS7VJZKUoMkn+3bUd77sWXa2nYDldsZzemm0q41Nr16fizsEhCnwvdEOrNRha` +
    `RNux5aHY9f0Qh63B3MyiXVvPp34eQmZcrZotclLmY8vt0msfOthDOHWjFNsxikMPx3` +
    `EAryCyI1CAYHBwikLP8/3YjpGb+kESxLvXHYaO56IoTWzHRTj2PRfHfoeRj9IgcRNs` +
    `Oz7C2MWef4xRakAKYrsPC7ZqtuzOsJarOJPKTw5W2n93GMV7CxaKw92SpVYDtWil6u` +
    `92bIU9G9XN/Ow4m2TlVVOC/SnoqikYHA3/njSFlWK9HNzDzwtoH0WxG8WR13ZFJ5qx` +
    `jyI/jKPkkmg+I5YrAFCKvSB1sY0TFCVBmLbCt8UQg+OiAKc4jHxf0bpemLq4E58oTI` +
    `MEp2pLRXGYejjsjc8Q4TBU0yXxPC/1gxaPtEbDbqyGApzIduG3tnk9keq7PWHaWv3U` +
    `xmZHetlz8MWLXeVzJ6c6v83/dv6/jvO7lCi0MQp1en+QA+3C5FiccLIi2WBW01qvos` +
    `5yFfQuV528Sy2qrRH+6dTrtJ5nh/NzK3xNFwhazi86RcaVft4Ji1raYTuCQG3BIWwA` +
    `e5cfBrR+T4H+uopeNeyzMmfLS1JRNRUjKCBQG/ACopOJsmcS5UQd2KqhF8NuVLxsAX` +
    `8mXa+J/Bkny51uIQrtWMlybQ9wYFqnzzOKUh1+T9rgVTYsnnKMWdI8H56vXSMCYwR2` +
    `jRXBgBVqCA6bMQWoQeGw6ThVtl9s0YRJef5sqNTDlXqxMUm1B9VTvvys0B/2Tjzonq` +
    `OpT0GGM/CdtABFieeHXqp2cRfjOArVzq67sO0i1/NDX+UTYRTEbqTWpyh2wyRpZwkY` +
    `paGXBp7tVE9YRWGAfPWI9dzyK562h3CgxbTGJ+oopkbZGPlKTpiqzEOJ8QLbAw/5sR` +
    `EfoEBL92ADHkqTRKv320no+0wMUKC7AhtHKIAEuYavbmqlW+rFKDaCNAP9NHBHhmpz` +
    `fOQZczBGsbZbSQixMgdwWHHTUtt4BsjXVmqBSs+B4Oph3mPSybCLUJIaHgGKQm2vSh` +
    `M17mFiYxTozggw8mwPJYb5YRBgrA7E1WtwK16RCo2wCodT7lIbITJ0doA8bIxxMNIP` +
    `WOmh/dYOP9cEmoqetBJRq2u7KK3ARmETo6GxqsXCcVFseDg1luGAnglSGwwKjH8dbB` +
    `wVqElTwec2geceBtXpmFWMK++5JvixXkJqKVB0kMe1ZO+I5t1FcHQjNvN20aBgWQ5s` +
    `zeGXbJOJKacruStVVG3Bp2Nr9x79IpQQ02jzWma0hDmneW+xQ73dlRRq+recMw5LIk` +
    `Q2J7sqSTVUrW0NldXmZMZNGM8JJzmYSkpVEmkxaI14zUrJWdFeDGsRU8mLj6ycNxIa` +
    `vs2bzo2KUn665pyUsthCNpV0Q0Cwct7SvyNAl6Ya7maAYvtJ9QMngv5GrDvd6tjQYZ` +
    `JxqS9iD7i80i8aNqZ5gk8xWS/72Kj+HRfV6mdyMPKeszknTY3xQOKqeX/I8KiapMhW` +
    `QuV/lTjliremD8QyKwrrzr318HEG+ZpnkrKyw+FN1Vmz8G6xt8eiXVhr3C0eqJwuYE` +
    `LkAyEl6PKvsDr+bmOjRH2m5AEm7PEDEStWCroh1jEoa/J3ysF7IOpZqvxLBcgFgaqm` +
    `q/f5vXgDGE3WUrJS22+u7es8Wtf2TEbdHVJVCStNTLn0nJLhPheA0VoQeCxo+eutqb` +
    `f+2658cDe6WQtyINksR90uY8JwkOxh99GUUI7jIfoInt36Wuqz2/8DZw8HirXtn2gC` +
    `/tIAVNWPawLQO0NXRba1QVdtgcgpOjk374tsS/gFs9MMUP8/gbCpUevFfmz10D471l` +
    `qBJyB91CJOzA16ZdMH0/yrW1WV9mtHmVbfNxkvZaDW4HmXCBPAHyVbnVoi9S1FhUsP` +
    `7fOvllrmCwBxz8mGsvVBytKOkpqkCZT+Mc8fHpxsXgSUn8njQfrRAsR8XVKB0UP77E` +
    `BoBV4CiA9kyTan9lJuCL4kGJOsfBEsXutrpeNQVNdOFRJ91M8OhVHhWTOMPWjes5yc` +
    `yh5UQvLjf/3v+7e3MKNlDpk6OUjC4SHbgmQg2XxeEJALKvrOjHuSPlS39hXGn8xgc1` +
    `EOS3awYXUiVVO9Mbn/F93lqtrDn3JTn21vS23aF7FmV6a4RvQNhUFVs9wLA907GAaa` +
    `6qsIA2PFNcNAc/xCYbBXn73ArH2X9zv9Y1Ul7Trd1Cb7nL6X0Gm6s9x+PaiOZ3fGln` +
    `6MelE65v4+K48EwIvZNRQEFxl4bni8rr9x6sZH9RnMcIBUhF9LhNSfbF09RCrGXy5G` +
    `Dj5Mul6QHO0wTZ2MkDIHNoPWRXjzIwFo36Dom8bP+1eLzZ3qhpKH+4rM2r9dJ6U8vE` +
    `Op70XUiPtsTsvunWzPq+ML/YxyTUmsux/V4/DWUJ/hzKD6ADc8Tp00zBiV2g/TF1mt` +
    `2LusX6/j99Q1BH0Xv/W7t6XklAiYM1gQTvZzxjOvx7RzSSn5FiRZropMEnigRQETot` +
    `5PSQ60lKyrVX8gtBXbNt4UrJx/YA/7dZkjeY2iroLxRC69t+6Roji5oK2K3ou3F5jh` +
    `J66p/tysvhiB3uPri2Bw/FB61YXtMI7uOWVXDSJOGW52VQWnObat4B9rst5tlCtO2Z` +
    `cA+vg92QvHmgLKOwDKfCv0lWBVfbj01cDlH8BlPkT6SuCqvor6ItP49SGCzZZTv//U` +
    `KaZ3egdK6T3MXnWL6t3uoZJ6H79Ocb3TO1Ba72H2Zr+Cvf+iYend+j2V8HPq2ro8OZ` +
    `DxVaXVnnzvyAa/K7f+wB5bX1U8tpODvnynUqf1y9nDEvfud7KG+pO5lm79Xtb8Qru3` +
    `3ts5Nq4nSyp768Z/pbLwcfA/ELEudsGt8jW69y1LF3euBzwhu6zG7+WWvQFlSL+6vF` +
    `HwV3lu3X3/90r2F1zJ2ovVG8rJVLJWdJ23XuX1uHdtGE/MmWYAVEQXzptewd150bw6` +
    `f3I0Q64+Q/Ki9xMTeImc5ORHJC+awuXF9daJna9OLBYN0c/ZkhxGhuptJo9qXDZ5+q` +
    `+Idv+AxM2E5VvdGN2Yf3TlnwEAAP//VOn6roVFAAA=`)
	if err != nil {
		panic(err)
	}
	container["templates/javascript.js"], err = decode(`` +
    `H4sICAAAAAAA/2RHVnRjR3hoZEdWelhHcGhkbUZ6WTNKcGNIUXVhbk09ALQ77XIbN5` +
    `L/9RSdya0ztChSkp3bHGU6ldhOna8Sx2Wldq/K5dodzTRJREOAATCitYn+3gPcI96T` +
    `XHUDmAGGQ0pOdv3D4gy6G91AfwI9N4WGWi1hDotGllYoma/NcgS/HgGUShpV46RWS3` +
    `55cXR3cUQIFV41wyhiAfmiqA2OIMGaTsGslLawUBoqVTZrlHayRPuqRvr57e3rKhfV` +
    `iMljTFpUjrJG22h5CJcnoplW1m7MbDo1tiiv1Q3qRa22k1Ktp780aIiqmf756dOnT7` +
    `88m67U9sSqkyXaE7vCk6K0TVGfaJQVaqxOFkrak+0K5Ymw5kQqe1LhQkisToQ8KY1h` +
    `fktjYo7RsTWGjVYb1PY2EWArZKW2xP4Ltd40FqtLe1tjhyWbuh7R+FuP/peibjBviX` +
    `2SmGdnX50/PZuWRV02dWHxxOJHe7IVlV2dbIVdnfxc3BSm1GJjp+dnp2dfPvmPJ5+H` +
    `HyzcEu1P+NH+lVBiKYnQGGh9LsU/0Ik4nZICLMUNyjE0BqEsyhVWUBbypjC891doLW` +
    `rYoF4ovS5kiQ4Pa4NjKDUWFkHi1uMcAfAKOwLzIwBIOJr4kd9+46F8aGzeKY2j7/Um` +
    `zxxANhpd+HlInO+Ktahvh+aKRgfni7FJKXLMsytV3WajMWSsSQsejSYslaSFJHjmxe` +
    `kFv8uz8ypjQA/E9GkL/JrDMWSbj5DBccR3ILxGq0VJwgfsNRam0Ujs8uYxaa+UHnrC` +
    `ivFJBjsp68KY74Wxk6Kqcn5yVlxUVVn3DGMMZW2crmC9g2o+zVdE+Hodz6zXD55Y41` +
    `rdYDc3oa9EhSm2Q3QCMbGMYLIOxazUdgiFORnEqIQprurBebCe+NEK5pCF31mLi/KB` +
    `qFki0+tqyK/SSI70mIozDE0jfWg/4zCCH+zjOBGGUdxYjHE0fXwEj8FshS1X5EK2W5` +
    `RQicUCNUoLNwK35ggeT48oZPlnmAefRI8gizXO4KqxVkl4/ZLMROD2bV3c1sLYGWT0` +
    `Jxv795dY6HI1g8zwj/b9S6GxtErfziC70mprUGfxqv2FpopkIpzE/bcj7i1wmMxWha` +
    `xqnJEpM8YFD5H+50T5GoR0QgUslsuv7dTrA4vpBDTwiNmZsi7TgMdy64M1zAHzaz8P` +
    `hJXNrzv6AGVhHO4MnEluYV3YciXkMibZCkEQLEJHl2mzytTJu1ZleIHM++sPyfCVxu` +
    `K6e1HhomhqO4sgKPyJqkJQdoXa9FnhsQFenLKnvARVfAArd0fd/7QkGyxFUUPBO2rg` +
    `qjBYgZJgVwgGayxtt1BhiTuNaNc4SzQr6+Qs1XpdyCr3qpaNIctGFzw1ygqKAHA0yG` +
    `1H22lzRJjSNFaX+TyBiLe/pyzeEih8ZOn61RMna95/vVBlY+K3d0OM0ss7Z+Y+bLy6` +
    `QRfoYv9tbzc4hoXs8kysJwGYfDlK1IH/gaE8EBiDS1Bp9jvOOyIka4tyxXh5piQpUD` +
    `svw4fc6x0aisA3SlVKuaDj3vS4Xgv53eUY1sXH7y4dc5xmkHPidyFcW84BsJ4IKVH/` +
    `508/fN8G8uJjyL04cgmULt0ggO1K1Aj5wsDzuZsLHj1KkpbccppmRpQlGHje0gtLtT` +
    `BwModzJ51P4A08c9QiIE/f7VnL1GNCJYXcIhR1rbagJMKmWKLbYoZmAXUjy8JyXOL1` +
    `d4S8APajndQol3YFz+GrT5bBW71VCmollzPOiaxPceifW16axdSixPx0DNGUJ3DWQU` +
    `Z8Wt3gRWTytDbteDd3vGsHZ3lCAmSPVljXYnORRervQrehQmDSpndzEpZzPBfHp48j` +
    `RdORpkGehBjH9t3F0ePpHoS8U0W27oEky3x7+4KypDfFGvPMkcjatFXQDw5PAuZweg` +
    `ECnpEETtQLEMfHYX0cao71e/FhDGfnYzj7KrIlpxtiuUT9bseCHA1fMVXCbCj8OOuk` +
    `EsHbaWDOeUZPLNgjEoxpnbKSSzC2WSzaybfmb0VV6TFsjTPt1LUGzC1eGVVeo3UVnx` +
    `+MeC3X1Riqwhadg/qM4nWI+0HnSVN/hRYa7ngxtmZC8+b/dfnjm4mxWsilWNwSoJtp` +
    `1mHMAl6cwLd7ThJsdbHZoAarXBHmmS0MFBKULGtRXhMcfizWmxpn5N03dXGbjSZ+FO` +
    `ZwZeWLEH54cAxnLr3uRg7Ivy/d8e9DZOuwLrowMJ1CAQvcwhfLWl0VtfmCRLG6KK95` +
    `LzZalWhImgrKRnMKaCwVjmrhAOriFrUrX182umAjmcPZ5NRlastXdbExbOOn7btLpu` +
    `CSRiIwg2xTNBR1/VFIQwkk7+OYBdxgYaMXRshlnUAUslLrGIJ90yn9lPjR+seQPi5f` +
    `aa00Odr3H/ybkJ1+J2qMBzQWFSUtl1gqWSWlzk1RN9iZ91qQ4JtCG3wtrRuFKfz7aW` +
    `vKBstdiD8FCFJjgngGZ6dhCx1GdkpO1mAZIkcoJYUkpzVrR4N4bykozOHMP35fGNu9` +
    `oj23K2FaQQzoRvKRAd6g5q1eojVQFjUVN/TylugrWbGebyraPbtCVmy/vYRVhf0Xkk` +
    `8c+LfXE0rcbpxXYKYclbdaLTWmZzq+MskzTzobJT6/tyF5UDBeQ8yzwMR9aEFZ27V3` +
    `WvneWeAHTtf4J4fIoMXPOi0PezSdgpClZlfu01GnKmLByk05PK2OVBYWQgqzQpdFtk` +
    `SPeV+6pGCAE2PVpk0ZyYf4hctGPpRtfeKSnf4p2023DiC0CwjTWLbHcHZ6StrlyZFN` +
    `of1JrFE1Nk93b0ywp6MusaQ6hE1s71lnl+uuCyEZNmt3Ym2W8BnV1EFgb6+TTWNW/q` +
    `DTsTSdwnev//uHVzOolbo20Czr29bYNr4u989Wt8+B3rrY5EPmDAx9PGcix8AjF94g` +
    `meqzKw3T525lnOKliYmx+uIorsfS5dtx1bzrnqk2OTvt8p4wZlZiESX/7TrnWSgU7v` +
    `bRm89jglSdOcwI724MX6Yb2YLtGujBXewth1v1riIM5J0akbY3iQvoYhsff+dZDOhm` +
    `6Hae4m7w8ZAr3T6IakT+aiWWq1osV844adB5oSBC2PDCcuSA1o2NfanC1uEefGwa+/` +
    `hKYcn/5gDkfrvo5H8ruXS/Aldsm3MOxKyKcSwM0TBipo2GA1PPEhZCUIynD3ExYY9j` +
    `4S5js4RFv8Zu/f8er3/+b78yf3ejv/NOhGqbXwYNcwWxC+qz+A25tFAcW7Vc1kiR9y` +
    `0BegpBueN0ImxJO9ZlFX5/wkhU7boZ2XOGGekhH5yBk5Md4tHblrD3O10YhLWqEEqr` +
    `6yOA95nfqGwMmdse+uU2hd/xVmQfDjgfb1ovhWHjcnnCMWQv3VFOMHUP9kqmUK9kDB` +
    `TFE4b40PkA551eCtMuiLPQVzL4hDiGhNEY3lHo4L07TM37G478l2SdgyburRAWosYx` +
    `FNoKY8dgheXH+qpZ/y285KcxbJQRvG2xIWGe0RbQPNlowug0n6jRjzoivbTAvfQQjN` +
    `QD4HeBAk2fjrPc/B6OIXfUKHbFfMPXkD3bXunn7ylRS0aOIfuQwQyy9vYh8qnuwLwL` +
    `i63Y8zmcnIV9bE9964FjFhkPsVserjr8VN3STqy65NIoH/UqSIlbWuM3qurdHY4Bpd` +
    `W3Y5D6oRvb3982gaSNZWoheks3HfrLCCWRGMipFmP+aHz3rqG9CfAAfa3gl4IMXVRw` +
    `DFK3L39pUN9e8lkbRdfPyS2+wLr+5rASHcT96ZB6TaegZH3rzn6dQnkdEQsQ9gvTnc` +
    `Hfy+O/Wk0Pzv7yYfl3Faffvp4hup338KXnOzQbJU2ibOrq51TF3MmhK9ZhDurq567+` +
    `j8d8JuYjFo2kAQs5hYkDFpUyXfho8622jh6MOTeoDS3BLD4y++HtS5LJqlLV4CHc8d` +
    `lhYs6LtrSSUEyYE8O/nWgh2/fVbG8TsuzCBfUaqYKvKwiAIfQlZXCbOkIbBSnwUWi0` +
    `ChZi2WgE1bCKbim1cgOswhstVHtDQkmZai8V3NW1O0WYzzkmU43lKkSaGIShbJle/t` +
    `Jg406Xns3P4f/+539BqnQiP8en0KZKjOgTuXtofNbR2GWlUo7UIAmfnQoDdlVYKJXW` +
    `WNqvk8shJukPIHkr+UU42ktAvUgQ7Tj/wRQsEtTDFm34nQS3x2Gjmy5JRLwPF8ntVO` +
    `LIaWe7QDEGYVyEp19vKLtOnLf7R+ErwKUXH870nVoq+YVfzd6JAQh3MhhpanzD0dNa` +
    `rhKJ1+g6JIohUQDrDOUV8Zu1IUxEqE76KytpFsIf8n6b+i2f6j1E5BCxPcnkKsdffN` +
    `McY8i6vYsp99IydhqO1OEzxX2xvb+cjnPaypTvlDcqFnY4a3/tWaR3PqUZZjSaq81I` +
    `oncD/LejEROd7fEpF0fVdXGN5FMojggJJWpbCMmJu4HcpeRwDF+PBnZdC3V2YNtpOB` +
    `tUFy3U+WHE872ITw4jPulr2mfhzCiUF+nWceoehNm9pg3c7h15clj9+CgfAT9u6kK6` +
    `DK64UjcYgRCT0SP4epHPebhEg99+i72XP/959ChFChZF0J33fDaH81EEmAqfWtzOCu` +
    `wMnx8efpIMD6xGl2CQq+zz4sP66az39p553L/ebX1E7+z8z/dS7At2mOL5l1/eS7G/` +
    `knso3iVPAXeft9JCUaFM81N2dNhtRQTP7yFIS/RJBJ/cQ/D0QeTuBtxjmqIVmw3Kih` +
    `1ri3nXnVL4o3uO2Jti2Ybw+FyfB2v/HAA2Gm+EaoyHcYRO3Fkz+JOfZOy4G+Nzg26C` +
    `OZzFitw1lWQLoR1Q7JKi8ZiJPSCBjz3DQaxueMfomNtBTu/ndcCC2z6VYQzev2hkj5` +
    `q4TP0dcosoK+BwrOTaPt6qZ4dk2LeeB8XYh+SvBuLBe0MzQF+yZDCmNhSpk1idLkKr` +
    `j8/nnXLvXYghrTm4CEMIvADdwB8VPlD6RMFb1b1f6l1juEfqIQSWuhv4o1K3XD9Y7L` +
    `ujpJrtjgjzXs0SNYtEjQv5/mrZtU69Q9PUtq2Z25Yq//6+qtgBg2borqRzh+G/wpLr` +
    `jFn/0rhz2bSnLMhAC0tya5NMBLVYC+tK23AsMFkXHx3T3anrXX+WWLbh655kUqksNx` +
    `YuVCOrbIfsLslPKhCHyj83PlR/uXkeUn3tS4iN/qaqsjT/Dx2/vgV1oTSzZqCoNRbV` +
    `bagne6cfwRiTalLIsm4qNK6iHPXzXl9qmJVq6opbs6oKijCzVeAKGRAWFlqtk2m/Hi` +
    `4Kh7v4rIzMdOcC8RCRnU6QrKiqbAy9EvnuIk5PevZyOEXZMc591lmFzsvvKfOJzDMd` +
    `2LHPvsavCvO20CiTCrU9I06pOeUaPDXu8NwpcFbV79TWUc56AOHs2KdhBHKRWFe6OH` +
    `tK4JazN8UaB85oIxN0c7hCCL5O3s0gm0yydpkB3vcpjyH7vKq/db2s/bumVGkG+LzZ` +
    `l9K0zbERN7EK7SZw+fAy1Gy0o0Tl+jowqHOxk0oQHu6l/IFwQB7vdVvh0CgttQmdez` +
    `JaCtnugv4ePdzVRIoCIjHkdXQC011u/F6V6xYhpvJHlOn3qlOYL62ckqd7I4FXqhjn` +
    `QV5zv9/c5zn3sHswI/td0e/3xL8/FgE/OQb+U6Pg/q24+9fvai8ephv6qY5qb8Z6t5` +
    `u73sWNU01dvcOFRrPq2rdpSG1Q/hWvLrkzdqBz1zjlghYm9+22oelVSSKRdM3ftPHT` +
    `99n8+PbVm6BLOy1C3KAYMxj3hJd87DfRWKuiyl1/8ELpEkF7aayCJVqoC4vGwsqua0` +
    `BbHkH3XYJns6xVet23y+eL73+8fBUYdaI3de0ek0yX7EcikwnN4KAxvHQ3C09Dx17b` +
    `Lj5qKSW70TWpR71cyb6M4alroIrlWaMx7pRlSKLeNadrS+YeUYKa8N1gjyD2O7Iicu` +
    `7OE2+sV7Suz9fbKJkdTIFbc2DqbrcqhUZ+YWGr9DUUBvDjBkuqRHIa4Usu/+FTuNEr` +
    `6pqN2Io1ulZlJrSjln6/XPviBffH+E5fyKjqcdGFh/2dAv0NZwg+2Lgv6gK6u8wIFw` +
    `QOwn1FdwgiFMTdd3Ebd50zzPCmvc15H/E5SDnlLgh3j0gpww9EGpCBd3GvEEy3P8n9` +
    `Qjx4YxIpHoy1K0avESwWKOoq69rR+o1jn9CRFvef0cOBo4S4ew3cUg9AO+ftP5zY+R` +
    `IqI3dIsWXHVL13doni1mSjiWszJTEpRLtAyV/XSRBy01hYCKwr93Ws+x7DzepMSfyD` +
    `1t5/gMJs7oIpLVBa9tTlqpDLFOMI0iDjC7m019e/nE45xIcobJVvE3f+4ejgB5XYff` +
    `4XhfHwSaf/VPLO6ZS7zRrDwa66Q710A41xw8kog40hw6R9bqj77jB+FTfp+YYTSvWa` +
    `q7Ww4du/ofQlcuL9/CR8Gdv/NtCpTPDzR7AzHvb5nz1P7GRb53ivF6NtrLGQ/Q1jXn` +
    `iKo+7uzq/8PaudLLM3QiX5a8hU5uisgA2MzzGhABfbXUMFhT6j1gj+c2MDOU5gOYEX` +
    `K63WOALTGMr0QDU6UAp99VFK0H1Y4ZzJvvuAZe/INFrf8BEwhdj422nfU/66yrP4NX` +
    `/sPnJhHtXi6P8DAAD//zdyZr9qRAAA`)
	if err != nil {
		panic(err)
	}
	container["templates/style.css"], err = decode(`` +
    `H4sICAAAAAAA/2RHVnRjR3hoZEdWelhITjBlV3hsTG1OemN3PT0ArDnrbuO41f/9FP` +
    `y02A+TYOxcdtKdKCjQNp0CBTrbYFIUBYr9QUtHNhuKVEnKjneRdy94k0lalJ1ksdhM` +
    `yHO/HzEX5+gvf/3X1y8lopw/9R3qJTQ9RX9ooSYY/bcHQUCi84vZbMnrHfp1htCeZg` +
    `lKgUANZwpJoFApwplBNlgGMG9wS+iuRMU3vuSKo6+c8eIjajnjssMV3J1fzA5QyWqt` +
    `gPey+IiqXkiygbuZx5LkFyjR9efu+W6GUIvFirASfbLHDtc1YasSXdpzxSkXJdpg8W` +
    `E+b7iAleA9q880bImrJ3v0CPubs7vZy2zm3PChJWy+JbVal+jH333uns+MIwaPaGtD` +
    `Zt9Bo/+zlo1q/aK5E9b16t9q18HvCwXPqvj5Y3TH+nYJIr3tsJRbLuriZyPbqXV1ef` +
    `m9sYmLGkSJrrpnJDkldcZ0gzYXuCa9HJy35M9aT+M/h7HkBjLfwvKJqPkERst/mQAH` +
    `PriC1jj34hxVvG05Q1LtqM2yxZKsjFkh/rU27WU2Wyw5rffQLegs0YJobeE6Wn17QH` +
    `/p6WWLKU3Bl4sfb5xGC1JxZuGE0hIxzuAu8LFGQ2jt5Loj34BoKN+WaE3qGpi+q4ns` +
    `KN6VaEl59aRvpBL8CTKJaIE+wz5/H9xRwuA/XCe4Qfd+0K6F2pcjrmuELYJzO/p/JE` +
    `EhtYYgy5HJR58h12/JEF9tV1G1zZdcKd46rNHKqm7OvO7P30B2nOmi9gbILVHVmrCV` +
    `bilbAKbrtm8Z+tDyJaFwhjCrkeBb9KEG+aR4d2aNGRzdULB5RuF5XhNhe1Hp+GgIpm` +
    `TF5kRBK0tUAVMgrEZrUltFOi6JpcJLyWmvAP0faTsuFGZKs1C8K9H89vb2tntOQBQa` +
    `NQ57mc2WvVIusYb+dB079PqwAnsmQd29N2KTuau7ztw4Zu+SpDhuLeZERDtBuOuHJ/` +
    `Uea/JcWE2MmoOPyrUuJ8ONd7giaqd1uDmtWzsWDa96+T4WNZF4SV2BpVyikVJ9yoyS` +
    `6vqUETJSDoc5LPh2mBma4N7Whi9+usU76QvmdVXhC5JvE2661E5j5ZSL8zrgu2iwDc` +
    `YGhCIVpj7fFO8sYgWuKSey7IhoMWFoJYjpXgtzinA1SCug/50raDuKFcytgbYK0FUj` +
    `fDXEWFgAlqXxebEwkr4IwQVaFOHdPWdKcDpyC0yhRXFKmAe9T1U0XLMo3vFeIbdNZE` +
    `0YNyJnxqghPsn2XH71TtOCyj37NOm/a5qr5qq5G8i9uBEGDhTjahUyuODa6MU5AlYj` +
    `3sRJ4bPES4ySJVTj1JzBveL2hw7IcJrOn0oJ+k8CW6R/eeRsNfFL8S6SB4p3IFDw68` +
    `IcvvIahl8KV1teROJaf7/HMtJGsPT9HusLxZ10fTFBdKBg5nyyoyMaJzf2zg5jCbQp` +
    `dUxzs8iL/XMvsPm2GJHrYYeCT5huOXW8YOfgEbEWssc03h/B0/cj2Zsmq9mGfbCGDI` +
    `7C95r0PS1X/0akSnLxEbCo1snlnwTfSijCBeIHvzKHvHJZpmExthWTw7fQmMLqkKOw` +
    `0MTPB/70TnZRjdwcRPr1fSL+kXN+WL76Z6DLo+JdcHwQsCG8l8HVT/CsguM3aPkGgo` +
    `t7CpiZEF2cHw1+VoeDNpPRpLAz6vwiqRTDMlst+mdaW8byLMXjfks4VCkvx2GklMaH` +
    `WSoNTSmcm7M0Fp5SmVjkiQx4JFeTtPTZajpLlKtDr3lHpk4nqZZwz5ns2/1I+QYdYD` +
    `UcHwlb0QCKWc3bIm6InkWmLzpwTOPEZEgsNKZwmmQoLDSRYZTNyjBQS6H4akXh7zaa` +
    `ZqDUUHE7cfQnWg1Cf6KPRDMKm4+lmbIrQYZQDmN3WKDdAugb7Sc/o14Va7+4TM8BXC` +
    `myAa3CP4iigI6ci5Tqj0Lprn/04pCQLvsWHTkHvcivHXuMB8FXAqRE0Q7g0i+1I4lz` +
    `As6vCuFaEK4kBwZnBVj4uyQY1+QFaPB7+A+OzIrwGK94XhwXOya1Jhv7djD9ab6vh8` +
    `uF2+78c4d70JhS6EWXH0ZS1xphCCOqg6ZLUF/5r983fR7k26hm7bc8aUwm3PxyD5QW` +
    `wUNI9Hh2/FMyVPl0Hd+u5bie/kvRaxM8cfkccS/wYWTtg+rLnmwxyBx7eTkp22zjxc` +
    `i+SXCxS0I83L8pzpMhHlh7D+4v3hfjA51PUvIdak4HOVLnlZGOaH+TcC8O7ElaVwpP` +
    `iPxz0ygFUIuuM0Sn0ANeEWa/PQPDXciGF1rfnNyFL4wxUf7+NSM9nOb+yd28RV8fe9` +
    `Xy0uwc9KdhXMZIbpjFxxTHjKPodMoD2MU5cg/39hkrds+k4f5/74DJTjaYinJGRfoH` +
    `e0PY0PZsMsEb9obcfE2kZ9jst4OjfMa2gAh4CpfcM0oKT/cJM2NTAVJhocKMdJPYPw` +
    `BfnKOebUCQhjRgl+CFrihy+M7krq2y7vDbd2vH2DcNd/zClNgVkehMW4mhr6zf6TKN` +
    `WT8I0mKxK8Zgj1BxVmOv8pE5MmLQsVrbV0LooIwvDOytnSzvDt98bQ36U9K1/LUrsf` +
    `iY4pjyiU4OY+j8P+EWUHQqktfCz+7PyK/sdAduzDrnh0ag60aYf493PP+KP+6s1CuH` +
    `Dsj4ddonp5+ClhprmGRSBLyL8MebZwxNKMbaZASM8XMNMYUbqppsguZUMrWeV2tC6w` +
    `+wAXb20cDdXpsCM584/k+o05zTXWla0thidfgXyymhvK6z1mhYzphT+J5qyxjuiCk3` +
    `w/4PvNH19r8AAAD//6WTZh/QJAAA`)
	if err != nil {
		panic(err)
	}
	container["templates/theme-default.css"], err = decode(`` +
    `H4sICAAAAAAA/2RHVnRjR3hoZEdWelhIUm9aVzFsTFdSbFptRjFiSFF1WTNOegBcik` +
    `EOgjAURPc9xSTdkZSqqGnKacpvESL4SVvThfHuBiQunLd7b2xkzngJQFcgXsbg0Uee` +
    `MeS8JKt1KaUuTaKBeUo18aynsdOlUXkIc1Ax+JpSQqWFAJTqHN1vkZ8PbyFDv9Juoe` +
    `cYfuGw7RvoaCGNN2RoFycLeTUruzj/Py4W0jlnnGnF+xMAAP//Q68dl8MAAAA=`)
	if err != nil {
		panic(err)
	}
	container["templates/theme-juri.css"], err = decode(`` +
    `H4sICAAAAAAA/2RHVnRjR3hoZEdWelhIUm9aVzFsTFdwMWNta3VZM056ADzMQQ6DIB` +
    `CF4T2nmMSdCaJVUfE0OkA11Y4BGhZN795oSWf5f5OnHFGANwMQOSAdq9FgHe2whHB4` +
    `JUSMsYi1x4Vo8wXSLrZ1FrHmYTG74c7oAr2HXDAGwPk84ePu6PXUCrJOo+7b8QJLzv` +
    `yhvO4HWCnIZIlGzincFGT9oJuhSqE5P5oB5ZRCe45LtJ0d2ecbAAD//9Kzz8TDAAAA`)
	if err != nil {
		panic(err)
	}
	container["templates/favicon.ico"], err = decode(`` +
    `H4sICAAAAAAA/2RHVnRjR3hoZEdWelhHWmhkbWxqYjI0dWFXTnYA7JhtSORVFMZ/M0` +
    `pJjS9QgRUxQ6G9EkKU+iGmDxYEQdLbh6IoiOjFwkIwM5qRIAqEwYygAokKNLCSXiAo` +
    `ybQyK8iVdZWFdVnd1X1xd51dlh13Z/+zXHkGrpeBda4L7gcPXP7e555zn+M995xzGQ` +
    `gRJhYLEyJEXQhqgVjM4DEGquCJENxiMOA+WNO71CW3xbL+vGJbfRzb4icmjL9oTAD/` +
    `AVPAHuAYsF9/z2l+ClgRNiP9P2Tf4sFfY66y9p7Ufn8Du4WPW/59C0wL/w0Yk/4+YS` +
    `948F8l2/ccPCn8Wgf/UPjlFtYh7HYP/jCQBT518N4CPEa+VAxs+RE4rr185AjwjYP1` +
    `AycK6P4AHLDmplAeBX7y5DayF9gFPG6NHcBhBzNjFpi35m/onD7YBP+i9tjMeMaTOy` +
    `77j4AmZzxXAHPHoOyv9uT/GjgDXGdhJqZtwKryM6zvY8C7QB9QLt0hxd9HqsXdb2El` +
    `wPfWub6p3MzPTa7cb+mbGvSnJ/872vNeB7/ROtd/lYP/a/6WpVcq//s8uEtVW6cc3M` +
    `7heuAv+XMrMKDY5KVWPrV78D8i2xctrFy51aPWnvenyrG9Qd8GIJCPFUXy/6r6Ytu1` +
    `OHEedGrqFcD7OvOEsFYPH2pk02thIdUg00vuAb4Qz7DW69XzjG+H9H3b04fXZX+3hT` +
    `UJ67CwHu17B/CZzuRJncOwlR8oX3OqhxeSvG6thX0HnAausbAHpPeJ+vCstVYh/WnN` +
    `83exzYPf1K6zqsM3CbsTWFKvexBI6z7kpVl7vHIR+I08pf9nGXhVNW1FtSGiuzonX8` +
    `2b4R9h5Zvgd98L9VYvMj35LmvtYeCc6tFB3YtOa70Y/kdlP1ngfXO9evxtBew6xTGv` +
    `u2FLSmsvbYDfyNPKL9P7b96gjcnRl4FKB+8S95Dq6kblId0vE+vGIuxseU3cpp6Ved` +
    `g3iv+kzvB51Z+Io1eqGDcr5z/XHQz0/r7S038U6xnnPROo3v0M7NRbwF5fFf5VgXj4` +
    `SpXyzfSkj4FRvTUn9P+2Kw9qiozztmyh2L8ZBBBdGw0L0aBhKZprXIznYG0EZtSFE9` +
    `lnL0tkWyOJzHIkkRlti2dGRqPpZFdluptUurs6lS6rTqWTpNK/d6VWFsZSmcR4ZTYe` +
    `RIOSpNknkRspWfc7xfkAAAD//yhdGif+EQAA`)
	if err != nil {
		panic(err)
	}
}

// Content for the given filename
func Content(filename string) (*[]byte, error) {
	if content, ok := container[filename]; ok {
		return content, nil
	}
	return nil, fmt.Errorf("file2go %s not found", filename)
}

// ContentMust for the given filename, panics if filename not found
func ContentMust(filename string) *[]byte {
	content, err := Content(filename)
	if err != nil {
		panic(err)
	}
	return content
}

// eof
