// Code generated by "file2go -v -t -o templates/files.go templates/*.html templates/*.js templates/*.css templates/*.ico"; DO NOT EDIT.

// Encoded files:
// → templates/icons.html
// → templates/index.html
// → templates/javascript.js
// → templates/style.css
// → templates/theme-default.css
// → templates/theme-juri.css
// → templates/favicon.ico

package templates

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io/ioutil"
	"log"
)

var container map[string]*[]byte
var filenames []string

// decode the base64Encoded string and return a *[]byte for the decoded data
func decode(base64Encoded string) *[]byte {
	gzipEncoded, err := base64.StdEncoding.DecodeString(base64Encoded)
	if err != nil {
		log.Panicf("failed to decode data(BASE64): %s", err)
	}

	var buf bytes.Buffer
	_, err = buf.Write(gzipEncoded)
	if err != nil {
		log.Panicf("failed buffer decode data: %s", err)
	}

	zr, err := gzip.NewReader(&buf)
	if err != nil {
		log.Panicf("failed to create reader from buffer: %s", err)
	}
	defer zr.Close()

	decoded, err := ioutil.ReadAll(zr)
	if err != nil {
		log.Panicf("failed to decode data(GZIP): %s", err)
	}

	return &decoded
}

func init() {
	container = make(map[string]*[]byte)

	filenames = append(filenames, "templates/icons.html")
	container["templates/icons.html"] = decode(`` +
		`H4sICAAAAAAA/2RHVnRjR3hoZEdWelhHbGpiMjV6TG1oMGJXdz0A7Fpfj9u4EX/3p5` +
		`jToUDvIHE5FKk/jrVAe1cgDy3ahyJA+yZbtK1GllxJduwU/e7FkPJaTryWvUgeVBwS` +
		`wKI0nPnNzI/kkNzZD7/+9Ze//+Nvf4J1uymeJzP6gSItV4mjS+d5AjBb6zSjB4DZRr` +
		`cpLNZp3eg2cXbt0ouc/qcy3ejE2VTzvNDeJz330u3WW6TbdF5oBxZV2eqyTZyjbq50` +
		`2+f607aq257gpzxr10mm9/lCe6bhQl7mbZ4WXrNIC52ga/QANOs6Lz96beUt8zYpq5` +
		`OBpj0W+nny9DP8qpfprmghX1QlmNfw89OEmeZ/JgDLvCimsNjVtS7bX6qiqt9NAIzV` +
		`KaDeUGut89W6fWlWe10vi+rTFNZ5lumS3mV5sy3S43ReVIuP7056y6rU1Gjauvqop7` +
		`XOzi2vsxH+rveuyEv9ryovp1BXuzJ7N/nvZDLftW0HdptmWV6upiC3B+q1SesVCXPb` +
		`nKeLjyvTcQo/6iX9M6+rg9fkn03HXdno1r6sM11PQWwP0FRFnsG8SC10+8mr0yzfNS` +
		`+2boak1YfWS4t8VU5hoctW1wTd5mj21GWDHk+0ms2r7Ngl6wfPg/cmkjZLWdqm4Hmn` +
		`VO5XkNZ56tlgJ05b77QDy2qxa4hhibNMi0Y7NrmJc8oExd55npxANMfNvCogzxKHjH` +
		`iLvF4QPYl/f6wOicOBg6D/HYdMLysFi0PiIHdgcbS/deJEzvPsyX5+PjtqjDy/ZpNw` +
		`DVncpu0assT5C/iuDx8AQ/gzYOgih3+SSfp+v8F01wz6WOtFa7ObONLpMps4KB04mD` +
		`fHxPHJNAne3Q/F9Y6DmEt9aO8PkjgHKb4aowtpxF5MozfGtNb7+/Fh1LOIwwjjs7h4` +
		`G76mrbaPpDw6py4ymQtM4oKHE9fotF6s7w8N5Ysp8F0Mr4SkP/J8O/JCM/AUU28Yek` +
		`XePMAqosl7kPABfPBv5iswkhiR6G3quXGnMoZ4QGV8UnlbEF1UnU5UgGpAqxE2ar8W` +
		`HYzfsioyXd8bwQ0IV8AaFBTgu4IpWIMxHMF7EG8ZdNWnYesraOu0bJZVvaFVIi2bIm` +
		`3177nriZ96ciecTZXl2yrLp+1xqxMnrRfO+R3xzkPFpC8UV06vM/SEjokjWMh9X6Hq` +
		`da7tKDq3zXi6rqNp05pmzZ64LrPE4ZfyJoceCoYxD2J0QxYqgWEo4Q8QuAFQQBA8jJ` +
		`kSwvdDN2Q89mUkw/PnC4We4CyII9fjDENfcAz9C0U+i2XEI3Q9nyFyFP5rimIbJBm6` +
		`12JRbV/W7ItuvVTVVUt58pDQ//Q1i7+YsFiozlMWzQY0acX0e0wcdWWhelrdzbN5Wn` +
		`7TkuDLIchpCMpX6X+lTKnKZrcZXMPvI7TPgpAHYSD6qbhgM/os8FUYRI+w+Q4udwFg` +
		`MQoZc3QxYkEkVdyjb08hgseZxBhV4Psky4WKOV7wk6lYRhjTkspCFQtUV/mpGCpFwy` +
		`USQsS+7OmIT9FwX7yGArzA5fC5794Vpvr8Ck17sx8tbG5gpj0PH57supx7WW4K3Oy3` +
		`5P//JP9SkikXmTLl/Vc10Jkmr/Gk1ludDlY1vfkquJiu5NXp6qLuokm118O/XXrdxn` +
		`k3nb834G+ZgiYvVw/tIsMOn7jhUQ8dugFIWoIV7AHF45sBg+8tof+2QL8p7dMyqzaP` +
		`lKI0FAMoQNICvIbgZqEsbKEc0Yat6/pw2C3Exybw74T1W0b+jp3lGZtiyg3JFncFoL` +
		`St2/sZkqTN700fROfD+i3bmE2eZcPj9dIJaZ1Abr2QA15QF1QvfQqgTmrYdYzJ94c9` +
		`mldte/9o6OBhBy+0LlF7EB7l8gNFfzg74WB6Xi19Cj1cgZ+tSRZEwlciplWcI4aBop` +
		`XdvEKXMy585VM9oQIZ8oDmpyDkKor6VQKyWIlYCtfrnpBYKJlPj2jGlt/pdAVDacz0` +
		`+ke0FaNeLjKf7KiYKg8yI6QrQDA/tOYlk8a6gD0IFkeRgff5ZuivuSiZNK+kiwGTED` +
		`Fu9ZqmAd2DF7LQGjIKzNPAGRk7ueMzYd1BZKHxmywoJHcAVafNWO3HUzLfeGkMEs4B` +
		`cl1RfsWlm7QLWBRbHZIFyvhLZaKJu4pcZNK8DACZcAWLrPKvSYBIG+LuM/BOV0DUUB` +
		`0dbqWLFkJm5VzJBFpnPGTmAQmHyVufftwSjdgTdyZOcF3O4i7YTL1wVFmveio8zkKr` +
		`wzvFUg3gjBgtMEza/HpoEyVp0HTh4y/E41+T6jZnSXGXPW7Jj2YKOVmB4iLyeLIsXk` +
		`E+OAmm2V1rbM/qy2QVspB8Fcql2kXRQ383wk0lT5MkyZipxPVCCEzzMgVC2frHUyxU` +
		`LrdKTaMvJ40F0sVd+nbL29fc/fdO7x5YxOxpJgqy9vox5ZfBQTeGNcTUaQ/8NumpDF` +
		`lD+LqsLop823RVujAnOKa6VA7QDtO+ob0lMmFmi67DdX9oDfPN4ezNQ8+NkZQ85pHr` +
		`Mx4EKhAB+CwUSHwTDP1IBjK+hvmScrOnZr/q8jHr7uO666ZlVbZek3/WU5B8e3jnmD` +
		`Slzpmr+xUsirRpbPKcuy6zet7sGg2HIi8/Tte1XibOj/3rq+fZ067pb8X2qxNiC/P5` +
		`LszfGay59xoJVHNjNg6s5qZsHFDNpdk4oJr7s5FAtTdu4wBrbuDGAbW77BoHWHs1Ng` +
		`6s87QcCdLTvcuo0J4PnMYBuzvAHhPYsYW4O6AeE9ixhbg7jx4T2IdCfN+25zvjHk9R` +
		`1h0xjwNsd3o8DrD2cHgcWNNsLNOXPUy6C+vsyf7V7uzJ/t34/wIAAP//HLd4rkguAA` +
		`A=`)
	filenames = append(filenames, "templates/index.html")
	container["templates/index.html"] = decode(`` +
		`H4sICAAAAAAA/2RHVnRjR3hoZEdWelhHbHVaR1Y0TG1oMGJXdz0A7Fxbk9u2kn7Pr+` +
		`jDfdlUSAzBO6dGs+XYzmar7KzLdnkvb5SIkRhThBaANKOk8t+3AJAUKFGkNNGMJ7up` +
		`OnUsgI2+fN1oNC6Zm3+8+ffXn//rw1tYiGV5+92N/AfKrJpPLFJZt98B3CxIlssfAD` +
		`dLIjKYLTLGiZhYa3HnJJb5qcqWZGIt6bQoiXNPpk62WjmzbJVNS2LBjFaCVGJibQnv` +
		`GbYpyP2KMmEQ3he5WExysilmxFENG4qqEEVWOnyWlWSCbcUHgC9YUX11BHXuCjGpaC` +
		`OgLKqvwEg5sbjYloQvCBEWLBi5q3vQjPNTiMWCLImTk7tsXQpz0D8cxxitiRdCrPj1` +
		`1dUdrQRHc0rnJclWBUczuryacf4vd9myKLeTj3RKBf3hPa2oVRuyL/627nec28eLKe` +
		`YLQeiaDwu5EYUoye1/kCm8//D65ko396EpZrRqQLnLNrKJihm1QGxXZGIVy2xOrh4c` +
		`RaYC6KqJoJspzbdQ5BNL/jDwg1XGOawyli2JIIzDHaNLWGZFheYUBIVFkeekgqJarQ` +
		`XcFaTM+Q6QvNjArMw4n1iLIictYjeaXMq75416gjwICzZZuSYT6/ff0T3/449Gk6u8` +
		`2Nx+t9Pq05d/BWmGlqX7+WYOGSsyR6s0sQRbEwvu6GzNZZhLTEpOLFDoTqy84Ksy21` +
		`5XtDI049vllJZKNSnAmRVsJqeInAM/0oeJ5YILnvxfOwbgRlPB7GFiYdeC2Vb/yyZW` +
		`Yt3eXOnPrYwrLaRpHxP9P2uyHpW8ysQC8on1HrDtw8+APRSH8AV8KVd+3KNtWyBHLQ` +
		`HbKSwglYM24B4Z1JDiEBYQH6clZVmseI2DVKSGIrSAPUws3cNkD/JCOb4e0G9PiELb` +
		`l6YADocVC1EYuKmb2D5yoyiMvAh8FHs4DbDtIewnQRSkfTrvu+LABzJCTneBr/TFMb` +
		`wDHNvYhf8+X2C25qNOZ2QmQKdgK7BgQWQWmVg4sOBB9WwnlgoASXjyOOz1DxzVudIz` +
		`90SQvB1IaS9G3SjABqbJIzFlZHPGPEoMiXhcw3RH7j1OPy7o6hyXJzvXJcpzkXJcdL` +
		`bjOMnYbHE6NNJfKATfxnEPJGYS9PXMj1UODFE4ngUPlCsLfkZU6ewXqHRxLPdpykjn` +
		`yWQgSTYs05plCukIy7RhOUyoUqjmicPhtCa5KmLF9pB0FL87WuaEnYrgEjzbgwWEUI` +
		`Jve0hmeiU4gZ/Be8yko/fj0ucgWFbxO8qWcr3OKl5mgvyzazve9wZdoyenebGieXGt` +
		`K4aMzaxdn4w7B4co8L3QDS1jMBhEW7UMub4fylWp7Wd6Fu3aaj718+AiYzJrGuSkyi` +
		`eW26VXPnSwh3DqRim25brp4TgO4BVEdgQSEAwOTlHoeb4f2zFyUz9Ignj3ucPQ8VwU` +
		`pYntuAjHvufi2O8w8lEaJG6CbcdHGLvY848xSjVIQWz3YUFXbfXUGWa4ilEh/eRgqf` +
		`33h1G8l7DUut+kLJkNZNJK5b/biRX2LFRX85PjbJpVF63O9qegK6dgcDT8eypGWvH1` +
		`8rTCbTSgfRTFbhRHnumKTjRjH0V+GEfJOdF8QizXAKAUe0HqYhsnKEqCMDXC12CIwX` +
		`FRgFMcRr4vaV0vTF3ciU8UpkGCU7mkojhMPRz2xmeIcBjK6ZJ4npf6gcEjbdCwW6uh` +
		`BCeyXfjNNK8nUn23J0zNGtJFoR2ptOfgs5Nd7XMnL9RWI//b+f93nN+lRKGNUajK+4` +
		`MaaBcmx+KEkRXJRqsaI19FnXQV9KarTt2Fws4If7j0Gtbz5HB+aoUv6QJeVPOzNvRx` +
		`rZ83YJGhHbYjCOQSLDfJ2Dt/M6D0ewz0l1X0omGfVTldnlOKyqkYQQmBXIAXEA0Wyp` +
		`4ulBO5YauHng27VvG8BP5Eul4S+RN2ljvdQhTasZTl2h7gQLeG9zOSUm5+B23wahsW` +
		`j9nGLIs8H5+vXSMCbQR2tRXBiBVyCA7bMSXIQeG46TiVtp9t0ZQKcfpsqNXDtXqxNk` +
		`m2R9WTvvwi0R/3TjzqnqOlT0nGK/CdtABFieeHXipXcRfjOArlyq66sO0i1/NDX9YT` +
		`YRTEbiTzUxS7YZKYVQJGaeilgWc79S8sozBAvvyJ1dzya562h3CgxBjjE7kVk6NsjH` +
		`wpJ0xl5SHFeIHtgYf8WIsPUKCke7ABD6VJotT7bRD6PhMDFKiuwMYRCiBBruarmkpp` +
		`Q70YxVqQYqB+jZyRocYcH3naHIxRrOyWEkIszQEc1tyUVBPPAPnKSiVQ6jkSXD3Me0` +
		`waDLsIJanmEaAoVPbKMlHhHiY2RoHqjAAjz/ZQopkfBgHGckNcfwa35hXJ0AjrcBhy` +
		`l1wIkaazA+RhbYyDkfqBpR7Kb2b4uTrQZPSktYhGXdtFaQ02CtsYDbVVBgvHRbHm4T` +
		`RYhiN6JkguMCjQ/nWwdlQgJ00Nn9sGnnsYVMMxKxnX3nN18GOVQhopUHaQx41k74jm` +
		`o0kwy09aYw2pbbJSFxAu8kJb1i6h/GHuRlxVycskKWlUKrGdGCLV7LrAC3X944QoDm` +
		`1XM1UNky5QEiQv15bfxqy9ueKbuXlbVdIsB7pm8Gu2yfiMFSuxuyOr25zNJtbuO/qV` +
		`SyG6YfJaZkUFc1bkvbds8uvuLquhf8sYZbAknGdzsrueq4dKl7RUlslJj5tSlhNGct` +
		`BXePVdnMHAGPGaVoLR0vRiI2ImWPmJVvNWQsu3/dI5P5LKz9aMkUqUW8hmotgQ4LSa` +
		`G/p3BKg70Za7HiDZfpb9wAgvfiPWrWp1bOgwyZhQx84HXF6pDy0b3RzgU07Xyz42sn` +
		`/HRbb6mRyM/MDonJH2cvtA4qr9fsjwqJqkzFZcVru1OOmKt7oP+DIrS+vWvfbwcQb5` +
		`mmWioFWHw5u6s2HhXWNvj4V5o9u6m98XYraAKRH3hFSg3h1wq+NvExsp6ktB7mFKHz` +
		`4SvqIVLzbEOgZlQ/5OOngPRDVLpX8LDmJBoH5MoBLUXrwB3EzXQtBK2a8vKZpdg7pU` +
		`1vuH7pD6errWRN/Tn3JXvc8F4GbNCTyURfX1Wl/0/5NxV3x7c7U2b1MbrFU+6nZpG8` +
		`ajZA+8T/rG6DggvI/gyc1vpD65/T8yen+gmGn/VBGw5wagvux5egA+lNlWBv1BHjIw` +
		`WB2heXIU1Gy8JAa9aUqaZ4O6qAciZmgwQUm8CDsjRekB8v9HELZArXgTq4f2yZFWCj` +
		`wC6aMWMaIvTWqbPurmX92q+jVH4yjd6nsR9VwGKg2eNkvoAP4k6GpomVAHUzUuPbRP` +
		`v2Iomc8AxAdGNgVdD+bLhqQNlP4xTx8ejGyeBZRfyMNBDWYAoh8U1WD00D45EEqB5w` +
		`DiI1nSzVA9wTTBtwRjmlXPgsVrdZJ4HIr6pLFGoo/6yaHQKjxphbEHzXuak6HqQRYk` +
		`P/3bf75/ew13RZVDJrdPgjC4z7YgKAg6n5cExKLgfRvnPUkf64uaGuPPerC+G4ElPV` +
		`iwOpGqqN7oDdA3XeXq66Y/5aY+295WyrRvYs3uZuoS0TcWBvU19V4YqN7RMFBULyIM` +
		`tBWXDAPF8RuFwd6V/Blm7bu83+mf6ovxrtP1dXSf0/cKOkV3ktsvB9Xx6k7b0o9RL0` +
		`rH3N9n5ZEAeDa7xoLgLANPDY/XzbO2bnzUL5/GA6QmfCkR0rzSu3iI1Iy/XYwcvEW7` +
		`XJAc7dBNVYyQKgd6B8ZtQPuf6IB5gqKOW7/sn6+2B8sb46zJ2r9iIJU4PEMxT576zn` +
		`ebb28rwQrCYU5hQRjZr4rGD4BW2byo9AG3IMtVmQnSb8OOsLXAGHsQ+easuysYFx+y` +
		`+dBKa9D8JH+eXXo3+84ROV0yuTdFp4tSU0Jf46jxbVox+m4BX+FhVeWGbETNHYncJJ` +
		`0NRpmNAr4jeZedBPfR40MV/KQSbLsLofuiLGFK5PcZyaGoBO3G9JEgM8J628LLaTX/` +
		`SO/3L++O2C6p68k6sNfYWxdIWQ4m/FXZezD5DBlw4Bjvz2W9sxHo3d4/CwbHN+0XTf` +
		`yHcfSBFfSiQcQKituqQ8Kpt7UrqP/7yDaZFfRbAH38HPGZY00C5R0ApZ/PvRCs6rd8` +
		`LwYu/wAu/TbvhcBVPxT8JtP49SGC7ZLTfH9T8Jm1P0h1Hr5B6Bn+mWWzrwfjde9pDD` +
		`ovPjq9I+89epi96r786HaPvfvo49d5AdLpHXn/0Yf0/jOL/Q8tS+/a73muccrjC3WF` +
		`PlKR19f/PfX4kQJj9yTgR/pgPP15MIuTvmq9Vsf4uwKH7zB2f0VAU3/W1wbGXxPQf7` +
		`+i901CZ1u/ni4L0fu24a/0dOE4+B8JX5e74Jb1YrH34KqLO1MDzt8bNeP3atvegNKk` +
		`L6NuPbeIOYkr7IcZe5Xn7ZKT5flZlQxcdMmB4xGZ5cfPDODYugMDxyO9y/UjEeyWgy` +
		`8Ww6Gq8EVg6O1j2CkUe3V+IdCOFJEvAl1/H91OXfmS0R2pOS+Jbl/h87x16vlV4kDN` +
		`+ghmf9evl6lfzRL1TcHITFCjpjitSs2bce9MGAcqpXYA1ERnVku9grvVkGR8ejUkqS` +
		`9+ijfte/AKz7H7HXzS+qyHBaog+uESO2vlooGM1cbCL9mSdMJAdrSTRDb+1CTZveI9` +
		`b5I0h83PPUdMuX9Pkf/XU6QJhUvPkP4rzN2fF7ya0nyrGjdX+k9y/m8AAAD//5fpcA` +
		`CjUwAA`)
	filenames = append(filenames, "templates/javascript.js")
	container["templates/javascript.js"] = decode(`` +
		`H4sICAAAAAAA/2RHVnRjR3hoZEdWelhHcGhkbUZ6WTNKcGNIUXVhbk09ANw87XIbN5` +
		`L/9RSdya0ztChSkp3bPcp0yrGdOl8ljstK7V6Vy5WFZpokoiHAABhR2kR/7wHuEe9J` +
		`rhofM8BwSJG+pC61/mENB92NbnSjP/AxN0xBJecwhVktCsOlyJd6PoBfjgAKKbSscF` +
		`TJuX15cXR/cUQIJV7V/Sh8BvmMVRoHkGCNx6AXUhmYSQWlLOolCjOao3ldIT1+ffem` +
		`zHk5sOQxJs1LR1mhqZXYhWs7op4Wxqz0ZDzWhhXX8gbVrJLrUSGX459r1ERVj//89O` +
		`nTp1+ejRdyfWLkyRzNiVngCStMzaoThaJEheXJTApzsl6gOOFGnwhpTkqccYHlCRcn` +
		`hdaW30LrmGN0bA1hpeQKlblLBFhzUco1sf9SLle1wfLS3FXYYom6qgbU/s6j/5VVNe` +
		`YNsYPEPDv7y/nTs3HBqqKumMETg7fmZM1LszhZc7M4+YndMF0ovjLj87PTsy+f/NuT` +
		`z8ODFW6O5ge8NX8jlFhKIjQEGp9L/g90Io7HZABzfoNiCLVGKFixwBIKJm6Ytrq/Qm` +
		`NQwQrVTKolEwU6PKw0DqFQyAyCwLXHOQKwI+wITI8AIOFo5Ft+/dU25X1t09ZoHH1v` +
		`N3nmALLB4ML3Q+J8w5a8uuvrK2rt7S/GJqPIMc+uZHmXDYaQWUua2daow0IKGkiCt7` +
		`w4u7Dv8uy8zCygB7L0SQV+zOEYstUtZHAc8R0IL9EoXpDwAXuJTNcKiV2rPEvaG6WH` +
		`HlnDOGjCjoqKaf0t12bEyjK3v9wsZmVZVJ2JMYSi0s5WsNpA1Yf5ighfLeOe1XLvjh` +
		`Uu5Q22fRP6gpeYYjtEJ5AllhFM1qLohVz3oVhOejFKrtlV1dsPViPfWsIUsvCcNbgo` +
		`9kTNEpnelH1+lVpypJ+pOP3Q1NKF9j32I/jGLo4ToR/FtcUYR+PHR/AY9JqbYkEuZL` +
		`1GASWfzVChMHDDca2P4PH4iEKW/w3T4JPoJwi2xAlc1cZIAW9e0TThuH5XsbuKazOB` +
		`jP5kQ//+EpkqFhPItH1o3r/iCgsj1d0Esisl1xpV0xZo6Qlkq/CcxWP6V2Ikkpiwku` +
		`DQtLi3YINotmCirHBCE91iXNgmmh05Ub4GLpzIActK7Ud+7K3FDoITX8Mjy87YWjo1` +
		`eCw3eljBFDC/9v1AGPf8uqUPUDDtcCfgJuwalswUCy7mMclGCIKwIrR0LW1rUFXyrj` +
		`EoO0D6w/XHpPlKIbtuX5Q4Y3VlJhEEBUdelgjSLFDpLiu2rYcXNxVSXoKh7sHK/VH7` +
		`Pw3JCgvOKmBWoxqumMYSpACzQNBYYWHagQpD3FpEM8ZZYndZK2chl0smytwbYjaELB` +
		`tc2K5RlMACwFEvty3txm77aLeG/Knk3VSKaFOOaK1xOk0gYuvq2KKfhhS7slQ91cgN` +
		`Zd59PZNFreO3932M0st752N8zHp9gy7KxsHD3K1wCDPRJrlYjQIwBRIUqAL/PU15ID` +
		`AElx1T7/c26YmQjGHFwuLlmRRkn02/Fj4kfu9RU/i/kbKU0kU896bD9ZKLby6HsGS3` +
		`31w65myOQ57Rvgu5grEJCFYjLgSqf//hu2+bLILdhsTPhk2OwuU6BLBe8Aohn2l4Pn` +
		`V9waNHScaUG5sj6gGlKBqeN/TCUM00nEzh3EnnqwcNzxy1CMjTdzprmHpMqGSQawRW` +
		`VXINUiCs2Bydii20FVDVomDGBkU7/o6QF8DcmlGFYm4W8Bz+crAM3qkYKaGSYj6xCZ` +
		`nx+RX9c8NLveiKF5ifDiHq8gTOWsiIT6NqvIg8Co1N0972HWttZy9PSIDs0QKriq8u` +
		`ssj8Xd6gqQoZNbnllIS1CWabRDgrU7GZtWZlZ2pPtqa/vntJ6dZbtsQ8cySyJv/l9G` +
		`AjGYcpnF4Ah2fEjWP7AvjxcZDVoeZYfeAfh3B2PoTzp84fffPmP797PQHDrhEo37bp` +
		`8ImdEUyTvprJ44yBz+eo3m9MGdeRr89KrlcUztx0pILET8wggevaEwsTEAlGN05eij` +
		`loU89mTedr/SMrSzWEtXZzOfWlAXONV1oW12hcfekbI16LZTmEkhnWeqTPKP6HPCIY` +
		`OZnmL9BAw70d+bUeUb/5f1x+/3akjeJizmd3BOh6mrQYk4AXlwvONr03Wiu2WqECI1` +
		`3J55llGpgAKYqKF9cEh7dsuapwQu6coko2GPlWmMKVES/jkJMN4cwl823LDvm3pU/+` +
		`fYhmLdZF6/fHY2AwwzV8Ma/kFav0FySKUay4trpYKVmgJmlKKGplE05tqEyVMwdQsT` +
		`tUrlh+VStGHMAUzkanbtrMX1dspe2kPm3eXVoKLkUlApQzspqiuF94qSldtXocWgFX` +
		`yEz0QnMxrxIIJkq5jCGsMzqlR4G3xv8Mc3n+WimpyLN++OjfhDzgG15h3KCQlZQEXW` +
		`IhRZkUVjesqrH1AUtOgq+Y0vhGGNcKY/jX02a+ayw2If4UIMiMCeIZnJ0GFTqM7JS8` +
		`qsYihIpQuHJBXmrStAbx3lEUmMKZU7BZcN1wrUHVwq5G4A0qq9c5Gg0Fq6huopd3RE` +
		`yK0hr1qiRVmQVaK/a6JKwyKJsLu5hhn71RUNZ341yAZchReafkXGG6XOSLnjzzpLNB` +
		`4tE7o58Ha7IDhnkWmHgILVhmM9DOBD+46fbRJmP20QbAYLLPWpMOChmPgYtCWefuc1` +
		`lnF3xmLZkKABodIQ3MuOB6gS5HbIgeW720Ib+HE23kqkkIyWH4gcsGPlCtfVqSnf4p` +
		`20ymdiA0AwjjWLbHcHZ6SqbkydEEQvMDX6KsTZ5qb0iwp4M2baQixs6nrcuobSa7ZF` +
		`xY2KzRxFLP4TMq14PAfnKOVrVe+DVUx1Ib7CoprzXU8+qumVkrX/L730Y1vwO9JVvl` +
		`fXMXLPTx1BI5Btty4WefpfrsSsH4uRsZZ3hp2qGNujiKi7l0+Db8stW6Z6pJvU7brC` +
		`a06QWfRal9M855FsqA+230ptOYIJV2DjPCux/Cl6kiG7DNCbpTi53hcKPelpOBvDMj` +
		`svY6cQFtILMr63kWA7oeWs1TkA0OHXKpmh+8HJC/WvD5ouLzhZuc1Oi8UBAhKJwZGy` +
		`agcWNDX4jY2eF++EA09MGUYpB/ttHGPbtQ5J+lmLunwJWdm1Mbda0pxoEvhL6ImSb0` +
		`9XQ9SVgIETDuPgTBhD0b+DYZmyQs+jF24//3ePzzf/nF8nc/+LvVRCjV7ctgYa7cdR` +
		`F8Er8hlxZKXyPn8wopzL4jQE8hGHecOwSVNG1tCuH1E1qiWtb1aD1n6JF+5L092Exk` +
		`g3j0tiHs/U4bBmEpS4TCqOoI4EPmFZUNIXPqoSenFPvOqiL7uMP5+Kn1qlkSRZ8YHE` +
		`PmX4bp7kFfi01I9y4ARnHFQnxsfYHzUp5wMzhutjoiwUfEMSVAdPEctRTPu8l02r+w` +
		`GcElzdreqe9nJ8x4hUNgynBthmC4sT+rq3r5Y3hpfw1hJTW36ownGOYZqYb6yQYji0` +
		`798Qp9qyPSSRfcSw9hkToA9l2gQN2n7VZu+x6OIXfUKKbFfMNXkD1bX6nnHyhbS1qO` +
		`IfuYwQSyZsMj8rVujb4Nl43Y0ymcnAW9NgvNVc/iioibrLvuLz18V+3Qjoy8tPVRPo` +
		`jWYEipAtc0xm9l2dmuHAIKo+6GIFSiWLeWwYOrKrku3JMtNdyjV7B7bTXfDmz0+GMM` +
		`F3yFd7S285AECMcd+u0SKZD4zal+s+JQ++ZuSLNX4QG6RmRfcvIXvIRjECpohmQK+r` +
		`BAP9eo7i7tAh0F7c/J277EqnrFddExMMKNk0I7KnsR+4Egu+ZK7wK53di7jH0n5ovd` +
		`E2k8BimqO7c07qaGt3Y+A26+0O0GxoM9/d4Tbrey9qswyrjA8OUZ0W394IrNuQgBqJ` +
		`kxKzbHIVRMm3f2qViWl0a16xqhhab7WaewF3VVBS0n9p61fWWfZvkrhTdc1toXknZV` +
		`8cTVLZQ3xK+P/eu+QfQrBgTeGT+Pmo1JOUHIxsd1BQ7urbeTGVfad7HV+e2FuEWICK` +
		`zfcTqdDSE7ywbxJE4G8dme0sRIhwrUg7tFphSyX6ywl+Gk879ixCg82NZE+MZMnjfq` +
		`3Uv+gHeo7B28LXK3UAfIHJB2yhts9iBhA/ChwnbwtgjbQh0gbEDaKmy/c3PLhO9Rr6` +
		`TQSU4gr35KUzy3reMWVmEK8uqndq02bvOFtC84qCWtN9BWoHG9wcVMttl/Uy43a569` +
		`JcMNKk2OchLvZ3z37hXJZGQhK/AQbm9jNzGX7Da0kkqKMEfaPjvRwC/W+JXHjofMsg` +
		`tXk1VoEGRVQgAMlUuyZNlU/nDaEA/rgLbnlXewwVycE/ZhIm9A3OiP2ojkZXqP9lxV` +
		`uwFpJznR+WzqTm1FG5ipVGy1QlFa4EG7XewfqLii8stImPF5rRBkbZOENZXvrsEmES` +
		`vFZbOFT4W/bHa93ckrtyw9ndq6Dx498quQNDrANWg09PLnGmu3XfFseg7/81//DUKm` +
		`Hfk+DqEtpLH0idwDND5raWyyUkpHqpeEXwHhGsyCGSikUliYr8IstrPLkvRbWFaP9k` +
		`XYUEpAvUgQmaX9gylYJKiHZU0pNwo5sXV0bXdJsevrAZ4cn0iqPdJsW3QMgWtXLdLT` +
		`W7w1aWbfWl+AS7fOnX9yc0eKL/xodlalgbutpmg6xXvknallVyKJ12hDPUq4omKotf` +
		`vXxG/WlEM8QnXSXxlBvRB+b4Su3tlton1EDjHGk0wOA/hzW9THELJWdzHlTqlvPZsj` +
		`tXuTalud2B1OxzmpMuU75Y3C7AZnzdOWQXrvy+OdEY7+NdVt9K6H/6Y1YiLaZF1w7e` +
		`qaJbtG8ikU7LiAApVhXNjFIQ25W/aBY/hq0KN1xeXZDrVTc9ZrLorL892I51sRn+xG` +
		`fNK1tM/CvkRYwkpVZ5eDgjCb54gCt1tbnuw2P7s3jIC3q4r5ooldyRuMQIjJ6Cf4NU` +
		`m7l2CXAeHXX2Pv5fcYHj1KkcKMIujWez6bwvkgAkyFT2fcxghsNJ/vbn6SNPeMRpsF` +
		`kavs8uJzj9NJ5+0D/bh/neNkEb2z8z8/SLEr2G6K519++SDF7khuoXif/Aq427yV4j` +
		`IbQkb9Uwq3221FBM8fIEhDdBDBJw8QPN2L3H2Pe9wj42qTzu6SbN6J69GRnOi0SN5N` +
		`e6O8151Qe4+6rkyT/TYn1/z7h/JbBwzKQn9KpuoIuJJnzzS1w2B/qur+Nhskv8Dc5g` +
		`WT7qmB+6RXl1hF9Ps355KNPSGNPUM6k7Uosw0WNkkelGr1JVKuvS+Tcf305DGbAeZF` +
		`WW4LL1q9KMutUWlrHNTqE+OgQ/yEOOgQ/z/iYBr3wtl4f1h7JpXVnQZWKWTlXUhdO9` +
		`Vg4LeTunJRVHWJ2qWv3dDRZjZ6IeuqtGcJyxJY6N1IcHkTcAMzJZdJ119ti2ovynKL` +
		`xwJvLpEj3Ngf34PgxuGmjJVlNoROku63Nv3jZmANmnDk//n08JvnJp0KoRN099Hkb8` +
		`1SryW860T8XWbRG+3/cJKEVGMvSZ78kSU5fVCO+6NDI/T2hCXNWKBJWMpwpeBbypii` +
		`jCVt2EhZuvF9wfQ7plAklW27EZNQc6G0d0OmxXNbi1lZvZdrRznrAIQNSZ8IEchFkk` +
		`ukg7OldG44e8uW2LO75tXc9uEKKPgqeTeBbDTKItf5oUt5CNnn/opG9xREapE9XN5s` +
		`OyTb3PmIeIkLyuh55/o7BY04t+7R/66M0PaeIOyfj/mV7oA83JqghYWmNC0hdHtWsK` +
		`GQbQ7np9jgphXSdOUxgLvX51dt2j3DTzW3dhBiKp9uSJ9qSqG31C0lv5pMclsSydJc` +
		`13rkA53xXnnOFmZ3JjsH5fgHyLyR4f/TpE+7cp/fQ6u7g2J42tNJba3e77dvX4UR6Q` +
		`bF5P3/NSbGxP5QITEw9ptHxIQw+bFV9fUfNSSuqhebQbGj/wdjYgy/f0gMWLui4G9g` +
		`Qp14tjOaHWgnjQgXO9X/++VDoastmj80fu3l57Z5uX4f18fhobZ2iGu7j+8p1FX5Hm` +
		`cK9aK9C0lNcoXib3h1aW+d9dyK0y5uQgOT+6tstr+1HklBJJIrqDeN+/PH2r9/9/pt` +
		`GNyNE/n28k/MYHzBsrArnyOFlWRl7u7ezaQqEJSXxkiYo4GKGdQGFmZZAZriCNpLvp` +
		`7NopLp8YxNPl9++/3l68CoE90fNOssVZI5CbRkws1KUBheuk3Wp+GCTHP3ctBQSrTR` +
		`3viMrk4kehnCU3dfIZZniVq7Qw59EnWOpbgrf/b+FUGN7FmODkHsXoCIyLkzKnhjvK` +
		`G1d+h8+kG2C2OwJ+Fh7Db6S4lafGFgLdU1MA14u8LCYAk5tdj9fv+RgnC4gVWVzU8M` +
		`X6K7BmgJbZil15e7LXRhj6P7W3SQKQzH0m2z316lv+EEl3c/7tsYAd3t64a9Ugfhvo` +
		`exCyJ8JqD9wsXK7Wz3M7xqNrY/RHz2Uk65C8I9IFLK8J5IPTJYLW4VwtLtdvKwEHsr` +
		`JpFib6xNMTr3LmKBoksc7e2P7j2NAy6AxNc96MfGjhH0XhYBN9Q90M55+0vJG58VyM` +
		`gdUtq8MVW9d3bJwlpng5G71UViUvXhagD7JQwBXKxqAzOOVem+c+PuOrte3VTi/6Cx` +
		`9zfALZubYFJxFMZ66mLBxDzFOII0yPi1qfRqnX85HtvqJQReI/2tTOcfjnZ+/ATbT3` +
		`VEkTt8fsV/1uTe2ZTb0BjCzkssu66u9Nw/6U9QLNgQMkxuqfRddNmNX8b3YfyGJlWx` +
		`9dWSm/Ahjb6MJXLi3bQkfOOm+6ENZzJtdOg2b5rjNd7Vq9QeoyLIfjejr4v2DuCT6O` +
		`MnB7DX3rmxtuMOqcwMCqiQldoebENRUkR2N1btNqtZ88KuQPkvJtXC8ArewIyL0oYe` +
		`T03CjN8CpwJ9/LhnHIK5/8bD/Xh81Ak4TaB40KOTSVfIRNd4j1wlUdUkW8eIH7C8xO` +
		`S8Q5LCfmYlFTzSuHU29tQkMHB5jjtnR2mAlksE/xElDTmOYD6ClwsllzgAXWvKekHW` +
		`KlAKV3qj9Ki9032UmEx6YHPojoFu3OUJrqY5Hhd/DcdfZ31T5slHcuwnvAYu5UE5O/` +
		`rfAAAA///wOwa4QFEAAA==`)
	filenames = append(filenames, "templates/style.css")
	container["templates/style.css"] = decode(`` +
		`H4sICAAAAAAA/2RHVnRjR3hoZEdWelhITjBlV3hsTG1OemN3PT0AtFp7j+O2Ef/fn4` +
		`JVkOJ2cfY+ctfceVGg7eUKFGjSw21QFCjyBy2NbHYpUiUpe51gv3vBl0TSoqzdRRHE` +
		`K/I3wxnOiyPqri7RX//2rx8/rxHl/KFrUSeh7ij6UwMVwei/HQgCEl1eLRYbXh3Rbw` +
		`uEBp4NKAUC1ZwpJIFCqQhnhthQGWBZ44bQ4xoVX/mGK45+5IwXb1HDGZctLuHu8mpx` +
		`Qkq2OwW8k8VbVHZCkj3cLTyVJL/CGt2+ax/vFgg1WGwJWyM3bHFVEbZdo2s7LjnlYo` +
		`32WLxZLmsuYCt4x6oLjW1w+WCHnmCYubhbPC0WzgxvGsKWB1Kp3Rp9/4cP7eOFMURv` +
		`Eb3bcLFvoNb/2Z3FWn+waj3p1QlrO/VvdWzhj4WCR1X88jaaY12zAZHOtljKAxdV8Y` +
		`uR7dS6ub7+1uyJiwrEGt20j0hySqrM1g3ZUuCKdLI33oY/aj2N/RzFhhtkeYDNA1HL` +
		`CYqG/zoBBza4gcYY9+oSlbxpOENSHamNstWGbM22QvpbvbWnxWK14bQa0APoKNGCaG` +
		`Vx7a2uOeG/9vyywZSm8PXq+/dOoxUpObM4oXSNGGdwN9j4evVREyK0c5L7Cb4HUVN+` +
		`WKMdqSpgeq4isqX4uEYbyssHPSOV4A+QCUYL+ij78G0wRwmD/3Ad5Ibc20KbFyqfkr` +
		`iqELYEzvTo90iCQmoHQaQjE5M+Sm5fEiU+427s8OrS5dxyw5XijaWzReA0w8r3F17/` +
		`x68gW850cvtNyANR5Y6wrS4tBwCm87drGHrT8A2hcIEwq5DgB/SmAvmgeHthN9Qbu6` +
		`Zg443C47IiwtaktVtHI5iSLVsSBY1coxKYAmE12pHKKtJySSwX3khOOwXod6RpuVCY` +
		`Kb2E4u0aLT9+/PixfUwgCrUax7SIVhDuSsesNLWmXgobbsb+T4vFplPKxWlf7m5GfR` +
		`PmY8ckqLvXOv9sKuhCtjQ2Hqyb5JujzAeH3eB6p9PKmuscac3LTs4jrYjEG+oSh7e4` +
		`JOqotXp/clyU7zLHRHk753gYCfHTuBT80J8HmuGTjXef1PSAj9InwfMi3ScZPySr6f` +
		`SZt5RTrg+yWxeAft1Vja3R9yAUKTH1jle8tYQluIKbyLLlv8GEoa0gpiqtzCii1ZBW` +
		`QP9dKmhaihUs7QZtSKKbWvjQjKmwACzXxubFykj6LAQXaFWEc584U4LTkVlgCq2KOW` +
		`7u9Z6raNhCUXzknUKuU8huYXwTuW2MbsQH2bDKb95oWtB6WD4N+m/q+qa+qe96di9u` +
		`ZAEHxbRahQwtuNJ4dYmAVYjXcVD4KPESo2AJ1ZgbM7hT3P5oh/Sj6fgplaD/JHBA+u` +
		`Ges+3EQ/Eqli8UH0Gg4HFlBj/yCvqHwuWWF5GY1s8PVEbaCJWeH6g+U9xKVxcTQgcF` +
		`B8A7W8Ojuv7eztkDVgKt19qnuUPBi/2hE9i8N4zI9dip4BnHTE4dL9gZeESsRQZKY/` +
		`0ROj0/Er1psJpO1zurj+DIfc8J33mx+nciVRKL94BFuUsm/yL4QUIyqQ1AiVSyCM/4` +
		`73ybHMrIRZ/GYmorPkdv0ZjD6pbjsGjM0SueY+oJEr+d+Mc7zUVJ5LYgcp5fd+KfnD` +
		`PDcqB/A13uFW+D4RcBe8I7GUz9BI8qGH6Fhu8hmPhEAbPCNu9ngymrw0nZymhS2DPv` +
		`8irJPLNkNvv0b5qrZudZjvuh6zhVKS/HUaScxoZZLo2mHM7MWR6Lp1zGF3kmA4/Eah` +
		`KWPlpNpYpita9dr4jU6SDVEj5xJrtmOKK+QgtY9cN7wrY0QDGreFPEBdYvkamzDo55` +
		`nJgMi0VjDqdJhsOiiQyjbFaGQS2H4tsthX9Yb5oDqoKS2xNMv39VIPSr/Ig3I7d5X5` +
		`pTeytI78r+GO8bctdQ+gL9zp95z/K1b4SmzxVcKrIHrcLPRFFAZ8ZFyvVnofRpcXbi` +
		`lJFuugadGQe1yLcxA8UXwbcCpERRT+HCL91H4ucEzrceYZsRtjgnG84KsPirJBjT5A` +
		`Vo+DXr94bMivAUz7iKHBc7JrUi+8wrfnRvG15KuG7R32XY6UmFnnT6YSR1rhGGMNLd` +
		`gklBPeXfpl/0upEvo3pp3zVKs2XCzcMnoLQIboLCK7YZr6ahyvN1fLmW43r6N0+vTX` +
		`B/FcRI+tZpL1+fBrZVL3PsJufqclbA2evPsxf/JgZ6z+uHF3l+0ul6VW9O8/w6X4dK` +
		`ztLq2XpNe9fLH/Hu9YR3Pdu0d2fVErda5nYigAZSfz2V0gGlE7WpxVvChpfW/9PdAy` +
		`pqIqT6greAWtelmkHZCQHMAgwe7QPFlrRINQz84aKmvwn2ddJNPC1Wg8TEKj2QmkUq` +
		`LCxvpGPCHmL5FcKNpf3WAOUck7tmWPU2Stb085lbgpU36UmE4HFT9LcLviamjH7+VS` +
		`2a/9piPkLcnrv69CJ/Frh86BWwrY4f9R2RvwP1gOtY4mERL/wDkeVAYRqQaDTnCvXq` +
		`ErnPOfYiNDbgzHzy/3s7TZ5iqeJT5kmtEO0x6CbDY64XkIkAjU31XLFemUUMOGuVsc` +
		`42AuesMt6/xuisdca61Aics0ru2jDF07pgesBMCRqSy3WK/oPH1SXq2B4EqUkN9iXN` +
		`nB/k9F7VTd/1ZyJ5Ydd4tncgQzfmhp+ZEsciEj1xGA7oc+rRhFq2MMRLfxGkweJYjG` +
		`H3UHJWYa/yjP4m2dCUkl7Rp9AaxkAZWxjsmZaY8d7cugtHm4N+lJRcP+1SLB6mNCZ9` +
		`olFg3Z9wA8g/FMmd+Af3DyGeWY1PjJc1yXe1QLe1MH/P12L/rWrcRKktTredseaYJS` +
		`YegsodK5K2MCF4F9GPV8YYTTjGamAExvS5apfihqsi+6DyrJnaLcsdodUb2AO7eGtw` +
		`91KVgmc+oU+vnHbu05LG2vzTz+9TQnlVZXejsdxm5qw7dy9jtCNbed+/VgKvdVr9Lw` +
		`AA//9pTyhVeScAAA==`)
	filenames = append(filenames, "templates/theme-default.css")
	container["templates/theme-default.css"] = decode(`` +
		`H4sICAAAAAAA/2RHVnRjR3hoZEdWelhIUm9aVzFsTFdSbFptRjFiSFF1WTNOegBcik` +
		`EOgjAURPc9xSTdkZSqqGnKacpvESL4SVvThfHuBiQunLd7b2xkzngJQFcgXsbg0Uee` +
		`MeS8JKt1KaUuTaKBeUo18aynsdOlUXkIc1Ax+JpSQqWFAJTqHN1vkZ8PbyFDv9Juoe` +
		`cYfuGw7RvoaCGNN2RoFycLeTUruzj/Py4W0jlnnGnF+xMAAP//Q68dl8MAAAA=`)
	filenames = append(filenames, "templates/theme-juri.css")
	container["templates/theme-juri.css"] = decode(`` +
		`H4sICAAAAAAA/2RHVnRjR3hoZEdWelhIUm9aVzFsTFdwMWNta3VZM056ADzMQQ6DIB` +
		`CF4T2nmMSdCaJVUfE0OkA11Y4BGhZN795oSWf5f5OnHFGANwMQOSAdq9FgHe2whHB4` +
		`JUSMsYi1x4Vo8wXSLrZ1FrHmYTG74c7oAr2HXDAGwPk84ePu6PXUCrJOo+7b8QJLzv` +
		`yhvO4HWCnIZIlGzincFGT9oJuhSqE5P5oB5ZRCe45LtJ0d2ecbAAD//9Kzz8TDAAAA`)
	filenames = append(filenames, "templates/favicon.ico")
	container["templates/favicon.ico"] = decode(`` +
		`H4sICAAAAAAA/2RHVnRjR3hoZEdWelhHWmhkbWxqYjI0dWFXTnYA7JhtSORVFMZ/M0` +
		`pJjS9QgRUxQ6G9EkKU+iGmDxYEQdLbh6IoiOjFwkIwM5qRIAqEwYygAokKNLCSXiAo` +
		`ybQyK8iVdZWFdVnd1X1xd51dlh13Z/+zXHkGrpeBda4L7gcPXP7e555zn+M995xzGQ` +
		`gRJhYLEyJEXQhqgVjM4DEGquCJENxiMOA+WNO71CW3xbL+vGJbfRzb4icmjL9oTAD/` +
		`AVPAHuAYsF9/z2l+ClgRNiP9P2Tf4sFfY66y9p7Ufn8Du4WPW/59C0wL/w0Yk/4+YS` +
		`948F8l2/ccPCn8Wgf/UPjlFtYh7HYP/jCQBT518N4CPEa+VAxs+RE4rr185AjwjYP1` +
		`AycK6P4AHLDmplAeBX7y5DayF9gFPG6NHcBhBzNjFpi35m/onD7YBP+i9tjMeMaTOy` +
		`77j4AmZzxXAHPHoOyv9uT/GjgDXGdhJqZtwKryM6zvY8C7QB9QLt0hxd9HqsXdb2El` +
		`wPfWub6p3MzPTa7cb+mbGvSnJ/872vNeB7/ROtd/lYP/a/6WpVcq//s8uEtVW6cc3M` +
		`7heuAv+XMrMKDY5KVWPrV78D8i2xctrFy51aPWnvenyrG9Qd8GIJCPFUXy/6r6Ytu1` +
		`OHEedGrqFcD7OvOEsFYPH2pk02thIdUg00vuAb4Qz7DW69XzjG+H9H3b04fXZX+3hT` +
		`UJ67CwHu17B/CZzuRJncOwlR8oX3OqhxeSvG6thX0HnAausbAHpPeJ+vCstVYh/WnN` +
		`83exzYPf1K6zqsM3CbsTWFKvexBI6z7kpVl7vHIR+I08pf9nGXhVNW1FtSGiuzonX8` +
		`2b4R9h5Zvgd98L9VYvMj35LmvtYeCc6tFB3YtOa70Y/kdlP1ngfXO9evxtBew6xTGv` +
		`u2FLSmsvbYDfyNPKL9P7b96gjcnRl4FKB+8S95Dq6kblId0vE+vGIuxseU3cpp6Ved` +
		`g3iv+kzvB51Z+Io1eqGDcr5z/XHQz0/r7S038U6xnnPROo3v0M7NRbwF5fFf5VgXj4` +
		`SpXyzfSkj4FRvTUn9P+2Kw9qiozztmyh2L8ZBBBdGw0L0aBhKZprXIznYG0EZtSFE9` +
		`lnL0tkWyOJzHIkkRlti2dGRqPpZFdluptUurs6lS6rTqWTpNK/d6VWFsZSmcR4ZTYe` +
		`RIOSpNknkRspWfc7xfkAAAD//yhdGif+EQAA`)
}

// Content for the given filename
func Content(filename string) (*[]byte, error) {
	if content, ok := container[filename]; ok {
		return content, nil
	}
	return nil, fmt.Errorf("file2go %s not found", filename)
}

// ContentMust for the given filename, panics if filename not found
func ContentMust(filename string) *[]byte {
	content, err := Content(filename)
	if err != nil {
		log.Panic(err)
	}
	return content
}

// Filenames returns the names of the files stored
func Filenames() []string {
	return filenames
}

// eof
