
// Code generated by "file2go -verbose -prefix ThemeJuri templates/theme-juri.css"; DO NOT EDIT.

package templates

import (
  "time"

  "github.com/pscn/file2go/decode"
)

const contentThemeJuri = `H4sIGKLgrlwA/2RHaGxiV1V0YW5WeWFTNWpjM009AFpXNWpiMlJsWkNCaWVTQm1hV3hsTW1kdgA0ykEKgzAQBdC9p/iQnRBTo5IQT2MmUxSUERPIovTupdRuHy9cIgWvBjAtSM6NE56XHFhLOXMwptba1SHTKrLnjuQw&#43;xZNHXRZ&#43;WB9ceooZ7SmAbSmPkDFhVzk&#43;Qc2QJHlnuwNQ4ByiZKfbhgDlH8s0f/H9B3Oj87OzfsTAAD//66raUahAAAA`

var fileThemeJuri *decode.File

func init() {
  var err error
  fileThemeJuri, err = decode.Init(contentThemeJuri)
  if err != nil {
  	panic(err)
  }
}

func ThemeJuriContent() []byte    { return fileThemeJuri.Content() }
func ThemeJuriName() string       { return fileThemeJuri.Name() }
func ThemeJuriComment() string    { return fileThemeJuri.Comment() }
func ThemeJuriModTime() time.Time { return fileThemeJuri.ModTime() }

// eof
